# docker-compose.release.yml
services:
  library-api:
    build:
      dockerfile: src/Library.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./src:/src/src  # bind mount — modifications de code visibles SANS rebuild complet
    ports:
      - "5259:8080"     # garde ton port habituel côté hôte

  sqlserver:
    ports:
      - "1433:1433"     # exposé pour que SSMS puisse s'y connecter directement depuis Windows