# docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: library-rabbitmq
    ports:
      - "5672:5672"    # port AMQP — utilisé par ton app pour publier/consommer
      - "15672:15672"  # interface web d'administration
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - libraryapp-network

  library-api:
    build:
      context: .
      dockerfile: src/Library.Api/Dockerfile
    container_name: library-api
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__LibraryDb=Server=sqlserver,1433;Database=Library;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__SecretKey=${JWT_SECRET_KEY}
    healthcheck:
      test: curl -f http://localhost:8080/health/live || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "8082:8082"
    networks:
      - libraryapp-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - libraryapp-network

  notification-service:
    build:
      context: .
      dockerfile: src/Library.NotificationService/Dockerfile
    container_name: library-notification-service
    environment:
      - SimulateEmailFailure=true
    depends_on:
      rabbitmq:
        condition: service_healthy
      library-api:
        condition: service_healthy
    networks:
      - libraryapp-network
    restart: unless-stopped

  library-gateway:
    build:
      context: .
      dockerfile: src/Library.Gateway/Dockerfile
    container_name: library-gateway
    depends_on:
      library-api:
        condition: service_healthy
    ports:
      - "5000:8080"   # LE SEUL port désormais exposé publiquement pour l'API
    networks:
      - libraryapp-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: library-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - libraryapp-network

networks:
  libraryapp-network:
    driver: bridge

volumes:
  sqlserver-data: